apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-fastapi-app
  labels:
    app: test-fastapi-app
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-fastapi-app
  template:
    metadata:
      labels:
        app: test-fastapi-app
        version: v1
    spec:
      containers:
      - name: test-fastapi-app
        image: ghcr.io/k8s-lovers-korea/test-fastapi-app:latest
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: LOG_LEVEL
          value: "info"
        # OpenTelemetry configuration
        - name: OTEL_SERVICE_NAME
          value: "test-fastapi-app"
        - name: OTEL_SERVICE_VERSION
          value: "0.1.0"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector.observability.svc.cluster.local:4317"
        - name: OTEL_EXPORTER_OTLP_HEADERS
          value: ""
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        # External service configuration
        - name: SPRING_BOOT_API_BASE_URL
          value: "http://test-spring-boot-app.sample-apps.svc.cluster.local"
        # Application configuration
        - name: APP_NAME
          value: "test-fastapi-app"
        - name: DEBUG
          value: "false"
        - name: PORT
          value: "8000"
        # Health check configurations
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        # Resource limits and requests
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
        # Security context
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
        # Volume mounts for temporary files
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
      # Security context for pod
      securityContext:
        fsGroup: 2000