name: Build and Push OCI Image with Kubernetes Manifests

on:
  push:
    branches: [ "main", "master" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main", "master" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Log in to Container Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Update Kubernetes manifests with image tag
      if: github.event_name != 'pull_request'
      run: |
        # Determine tag to use
        if [[ "${{ github.ref }}" == refs/tags/* ]]; then
          TAG=${GITHUB_REF#refs/tags/}
        else
          TAG="main"  # Use main tag for consistency with app image
        fi
        
        # Update the deployment manifest with the correct image tag
        sed -i "s|IMAGE_TAG_PLACEHOLDER|${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${TAG}|g" k8s/deployment.yaml

    - name: Create OCI artifact with Kubernetes manifests
      if: github.event_name != 'pull_request'
      run: |
        # Install ORAS CLI
        curl -LO https://github.com/oras-project/oras/releases/download/v1.1.0/oras_1.1.0_linux_amd64.tar.gz
        tar -xzf oras_1.1.0_linux_amd64.tar.gz
        chmod +x oras
        
        # Determine tag to use
        if [[ "${{ github.ref }}" == refs/tags/* ]]; then
          TAG=${GITHUB_REF#refs/tags/}
        else
          TAG="main"
        fi
        
        # Construct the full image name
        MANIFEST_IMAGE="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-manifests:${TAG}"
        
        # Push Kubernetes manifests as OCI artifact
        ./oras push "${MANIFEST_IMAGE}" \
          k8s/:application/vnd.k8s.yaml \
          --annotation "org.opencontainers.image.title=Kubernetes Manifests for ${{ github.repository }}" \
          --annotation "org.opencontainers.image.description=Kubernetes deployment manifests"
        
        echo "Pushed Kubernetes manifests to ${MANIFEST_IMAGE}"